version: '3'

volumes:
  database_data:
    driver: local

services:
  db:
          image: postgres
          restart: always
          environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          ports:
                 - "5432:5432"
          volumes:
            - database_data:/var/lib/postgresql/data
  web:
          build:  .
          command: python3 ./src/manage.py runserver 0.0.0.0:8000
          volumes:
                  - .:/src
          ports:
                  - "8000:8000"
          depends_on:
                  - db
