# Generated by Django 2.0.10 on 2019-02-06 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_image', models.ImageField(upload_to='owners/ids/')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('trademark', models.IntegerField(choices=[(1, 'Ford'), (2, 'Volkswagen'), (3, 'Toyota'), (4, 'Hyundai'), (5, 'Chevrolet'), (6, 'Honda'), (7, 'Kia'), (8, 'Mazda')])),
                ('type', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Owner')),
            ],
        ),
    ]
