# Generated by Django 2.0.10 on 2019-02-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='id_image',
            field=models.FileField(upload_to='owners/ids/'),
        ),
    ]
