# Generated by Django 2.0.10 on 2019-02-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20190207_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ('name',)},
        ),
    ]
